apiVersion: v1
kind: Service
metadata:
  name: frontend-entrpoint
spec:
  selector:
    app: ecomfrontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomfrontend
spec:
  selector:
    matchLabels:
      app: ecomfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ecomfrontend
    spec:
      containers:
        - name: ecomfrontend
          image: sajidhm/iphonemax-frontendecomfrontend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
